[general]
# Interval to run at in seconds
interval = 21600 # 6hr

[eosio]
# The API server for blockchain requests
# api = 'https://fiotestnet.greymass.com'
api = 'https://fio.greymass.com'

[signer]
# Authority submitting pricefeed transactions
actor = 'xxxxxxxxx'
permission = 'xxxxxxxxx'
key = 'xxxxxxxxx'

[multiplier]
fee_multiplier = "1.00000000000000000"

# Target fee prices in USDT
[fees]
add_nft = "0.20"
remove_nft = "0.10"
remove_all_nfts = "0.20"
add_bundled_transactions = "2.00"
add_pub_address = "0.1"
auth_delete = "0.05"
auth_link = "0.05"
auth_update = "0.10"
burn_fio_address = "0.20"
cancel_funds_request = "0.10"
msig_approve = "0.05"
msig_cancel = "0.05"
msig_exec = "0.05"
msig_invalidate = "0.05"
msig_propose = "0.20"
msig_unapprove = "0.05"
new_funds_request = "0.20"
proxy_vote = "0.10"
record_obt_data = "0.20"
register_fio_address = "2.00"
register_fio_domain = "40.00"
register_producer = "30.00"
register_proxy = "2.50"
reject_funds_request = "0.10"
remove_all_pub_addresses = "0.20"
remove_pub_address = "0.10"
renew_fio_address = "2.00"
renew_fio_domain = "40.00"
set_fio_domain_public = "0.10"
transfer_fio_address = "0.50"
transfer_fio_domain = "5.00"
transfer_locked_tokens = "0.50"
transfer_tokens_pub_key = "0.25"
unregister_producer = "0.05"
unregister_proxy = "0.05"
vote_producer = "0.05"

[[log]]
level = 'info'
out = 'stdout'
